import React, { useState } from 'react';
import Sidebar from '../components/Sidebar';


const personalities = [
    { type: 'INTJ', description: 'Mastermind Secrets Revealed',details: `INTJs are strategic and intuitive thinkers and thorough planners. They exude a quiet confidence, intellectual insight, and knowledge. They are usually nonconformists who don't mind being different from the crowd, thinking for themselves, and rejecting long-standing traditions or rules that make no logical sense. They might intimidate you at first; they may appear intense and aloof. They don't come across as needy, and even the pretty opposite, fiercely independent.
    People with INTJ personalities don't settle with the knowledge fed to them at school or by books. They genuinely want to learn more and continuously expand their knowledge by trying to understand everything about the world. They savor the sensation of whole immersion into their studies and can easily spend hours doing informational research. INTJs are insightful and quick to absorb new information.
    INTJs thrive in a world of ideas and strategic planning. "Supreme strategists" are what they are often known for. Whenever they encounter anything, ideas and concepts run through their minds on how to turn it into a rational system. They are like this because they generally dislike messiness or inefficiency.
    However, INTJs are not the greatest in dealing with people or building relationships. They often have little to no interest in other people's thoughts or feelings. For INTJs, what's most important are intelligence, knowledge, and competence. Consequently, they may sometimes appear arrogant or elitist. They are most commonly drawn to contrary viewpoints and tend to express their judgment, even if it may come off as impolite or rude. INTJs do not do well in expressing their ideas. This is one reason why they are commonly misunderstood. But beneath their cold exterior is a deeply emotional person, but just as profoundly loathes to express it until you’ve already built a very close relationship.
    For INTJs, practicality is the best way to go about things. They dislike waiting for others to catch up because they know they don't need them. Most often than not, they want to make decisions by themselves. They don't want to be influenced by the status quo or anyone else. They believe that when they want something to be perfectly done, they should do it by themselves.` },
    
    { type: 'INTP', description: 'Intricate Mind Labyrinths', details: `INTPs are quintessential philosophers and independent thinkers. They are logical, objective, open-minded, imaginative, original, honest, and low maintenance. INTPs are addicted to new information and a never-ending search for truth. Not often one to sugarcoat things, they can sometimes leave conversations with awkward silences, but you can count on their honesty. But beneath their aura of intellect and busy mind is an intensely loving and loyal heart.
    INTPs like to relay their ideas and thoughts with no filter, which is why they are often misunderstood. They like being straightforward and upfront because, for them, being upfront isn't rude but rather a point of pride. Being direct can avoid misunderstandings, and time could be saved and put to more practical use. They might come off cold, mysterious, and hard to pin down, but they want to offer emotional support to people close to them; the problem is, they don't know how. Most of the time, they dismiss subjectivity and are often clueless in emotional situations.
    They value knowledge more than anything else. INTPs find joy in observing and theorizing about everything they see around them. They try to find the meaning behind things. As a result, they often impress others with their unique perspective. Behind their calm exterior, they are very passionate about reason, analysis, and innovation. The mind of an INTP is fascinating because they perceive the world as a vast machine made up of numerous parts that all seem to fit together.
    As introverts, they prefer being by themselves, reflecting on how things function, and formulating solutions to issues. Behind an INTP's introverted personality is a vibrant inner world where they can pay attention to their inner thoughts rather than the outside environment. They enjoy time alone; thinking in silence for them is equivalent to extroverts' going out to parties.` },
    
    { type: 'ENTJ', description: 'Bold Commanders of Success', details: `ENTJs are masters of efficiency, formidable, confident, and a force to be reckoned with. They like being at the forefront, taking on life's challenges head-on, and moving the world forward. They're intellectual, confident, and visionary, making them extremely attractive, especially to those seeking direction.
    Natural-born leaders, ENTJs have an innate passion for guiding others toward ambitious goals. They are comfortable taking charge, sometimes even without knowing it. ENTJs can detect complexities and instantly visualize a path to take to get over those. Their decisiveness is a significant factor in why they are excellent leaders.
    ENTJs are organizers of change. There is no place for errors or inefficiencies for ENTJs because for them these will hinder them from changing for the better. ENTJs are assertive and innovative and enjoy planning and setting long-term goals. This way, the future will not be uncertain or out of track. ENTJs thrive when there is predictability and control, that is why they make sure to keep everything structured and organized as early as possible.
    Excellent with verbal communication and humor, ENTJs have no trouble making friends. However, they may sometimes neglect other people's feelings and opinions, especially when making decisions. ENTJs would much rather not have to deal with other people's emotions and can often struggle to manage their own. ENTJs are strong characters who prefer to not to show their feelings.
    Rationality and incredible problem radar help ENTJs prevail against any challenge. ENTJs see problems before they happen and cause more problems. Being able to see a problem early on will give ENTJs ample time to come up with a solid plan of action. Fantastic logical reasoning and quick thinking allow ENTJs to thrive in all the challenging situations that may come their way.` },
    
    { type: 'ENTP', description: 'Unleash the Chaotic Genius', details: `ENTPs are innovative, charming, and witty. Their quick and restless mental energy and enthusiasm about the future are contagious and attractive. Rebellious and brave, they aren't bound by rules and can be frequently found pushing the boundaries, challenging traditions, and blazing their path. They've got humor, brains, and imagination. They may forget the little things in life, but their passion and excitement for the future make us realize those details don't matter much.
    For ENTPs, there is always a solution to every problem. Innovative, clever, and expressive, they are often labeled as logical powerhouses. Mapping out complex ideas and analyzing are some things that they generally like. Understanding and influencing other people are some of the things that ENTPs particularly like doing. They believe in their capabilities and are not afraid to utilize them at any time.
    If other people can see things the way ENTPs do, they'll see the world from multiple perspectives. All of which are equally interesting and worth pondering. ENTPs generally take on things with more depth and understanding. They love sharing what they know with the people around them.
    As intellectuals, ENTPs use their wit not just to solve problems but to understand other people too. They are versatile, open-minded, and restless. ENTPs tend to have a "wait and see" attitude because they don't want to shut their doors to possibilities. They constantly crave novelty due to their limitless interests.
    Rules are just limits; this is a fact for ENTPs. They would gladly challenge the standards, question norms, and even break the rules if they see that it will take them to where they want to be. They are high believers that there is always a better, faster, and more exciting way to deal with things. They like taking risks even if they know it could lead them to failure because, for them, failure is an opportunity for growth rather than disappointment. They love cheating the system and looking for gray areas that they can take advantage of to make the rules work in their favor.` },
    
    { type: 'INFJ', description: 'Explore the Enigmatic Mind', details: `INFJs are principled, generous, and talented communicators. They hold a passion for doing good for the world and for the people they love, driven by their deeply held principles and values. They are one of the most loyal, loving, and supportive partners. They are visionary and see the world as what could be, and are continually drawing insights that explain how people and the universe work. But at the same time, you'll find them adorable and endearing as they could be doing this while bumping into things or forgetting to wear matching socks.
    Known to be artistic and creative, INFJs have overflowing ideas and imagination. They translate their ideals into different art forms where there could be layers of hidden meanings and possibilities. Their minds are truly creative dens.
    INFJs have the potential to be better at handling other people's emotions than their own. Most of the time, they have no control over their feelings. Because of this, they are naturally gentle and don't want to hurt anyone. They are conflict-averse and sensitive to problems and tend to internalize them even days after.
    Being the rarest personality type in the world, INFJs often feel like they are aliens living on earth. Because of this, they are often misunderstood. INFJs don't like fitting in or compromising their ideals. They have strong, uncompromising morals and always act based on what they believe is right. Even as true introverts, INFJs could be mistaken as extroverts because they can also be social chameleons. They can blend into social gatherings because of their inviting attitude and ability to get along well with others.
    INFJs see to it that they find opportunities wherein they can step in and speak up. They crave moments where they can make a difference. For this personality type, success is not measured by tangible achievements but rather by fulfillment, altruism, and good done in service of the world. As people who care deeply about integrity, they won't stop until they can fix problems in society. With INFJs' creativity, imagination, and sensitivity, they seek to uplift others and share compassion for others.` },
    
    { type: 'INFP', description: 'Poetic Dreamers Unveiled', details:`INFPs are optimists, always looking for the good in people, even in the worst situations. They're accepting, open-minded, imaginative, and spiritual. They are guided by their inner moral compass and the desire to do right by their values. They desire a life of meaning, personal significance, and individual expression.
    Overly idealistic, INFPs often daydream and fantasize rather than take actual action. They look for the "what could be" instead of focusing on the "what is." INFPs are creative and imaginative; they have a childlike inner world that is vast, lush, and filled with magical transformative possibilities. They tend to disappoint themselves. After all, they are idealistic because they want to see what they have in mind in the real world, which is often not the case.
    INFPs like dealing with things based on how they feel about them. They have their personal values system where they decide based on their emotions instead of what is right. They generally dislike details, but they are willing to compromise if it is for their cause. INFPs would lean into seeing the bigger picture instead of going through the little details. Because of this, they don't like dealing with hard facts and logic.
    Many people may not understand their uniqueness but they are okay with that and enjoy it. They have no intention of pretending to be somebody else. INFPs are committed to authenticity, and because of that, they often look for opportunities where they can fully express themselves. They are some of the most open-minded and open-hearted people, but deep inside, they tend to be too hard on themselves.
    Despite being introverts, INFPs are adventurous. For them, adventures and new experiences are opportunities to learn more about themselves, the world, and their purpose. As long as the adventures stimulate what they believe in and live for, they are always ready to take a chance. They think that these adventures are part of their path.` },
    
    { type: 'ENFJ', description: 'Empowering Inspiring Leaders!', details: `ENFJs are people with others' wellbeing at the heart of their purpose. They're diplomatic, polite, and skilled at managing relationships. They have a gift for understanding others' feelings and motives and do their best not only to keep the peace in their communities and relationships but to anticipate and support others' needs. Nothing gives them more satisfaction at the end of a day than being appreciated for all the hard work they do for their friends and loved ones.
    Warm, outgoing, loyal, and sensitive are some of the words commonly used to describe ENFJs. People with this personality type are renowned for their exceptional capacity to uplift others and effect constructive change in the world. They are emotionally intelligent people who can read what people around them feel. They are willing to do anything for the people they care about. As a result, they are frequently said to be one of the most selfless people.
    Principles and ethics are extremely important for ENFJs. They are the people who will fight for what is right no matter what. No one can convince them to do things that are against their morals. They do not tolerate injustice and wrongdoings. Their excellent communication skills come in handy during these times. ENFJs are like this because they genuinely care and want the world to improve. They also use their charisma and natural influence to encourage others to stand up for what is right.
    If there is someone who can gather people and encourage them to work together for the common good, they would probably be the ENFJs. ENFJs are good at bringing consensus among diverse people. For this reason, they can be outstanding leaders and bring enthusiasm to a group that can be motivating and inspirational. They are leaders who inspire and help instead of dictating.
    ENFJs frequently do best in settings and circumstances where they can help others exhibit their full potential and engage in social interaction. People with ENFJ personalities are great problem solvers, too. They excel at settling disputes and fostering unity. ENFJs make great public servants, leaders, counselors, teachers, and influencers.
    ENFJs' capability to bring positive impact to other people is what sets them apart. They are excellent communicators who frequently exhibit warmth, affection, and support. ENFJs excel at motivating people and find delight in doing good deeds. They experience the same happiness when they see those around them achieve in life.` },
    
    { type: 'ENFP', description: 'Boundless Energy Unleashed!', details:`ENFPs are free spirits: energetic, enthusiastic, and curious. Their engaging, warm personality is made even more endearing by their imagination and creativity. They are fiercely independent and enthused by the possibilities, the unknown, and the world yet discovered. They will stand up for their ideals and for the principles they believe in.
    Some of the most versatile and talented among the personality types, ENFPs are bright people who are full of potential. They are typically drawn to creative endeavors, like art and cultural interpretations. Since they are some of the most skilled, they are highly adaptable to change too. ENFPs are great conversationalists masters of talking their way out of their many prior commitments.
    ENFPs believe that everyone and everything is connected as if life is like a massive chain. They give an ample amount of time thinking about the possibilities that these connections might bring. The healthy balance of their imagination, creativity, and curiosity makes them who they are. ENFPs have great charm, ingenious ideas, and across-the-spectrum capabilities, making them independent and outgoing.
    If there is one thing that ENFPs fear, it is boredom and stagnation. They don’t like it when they are mandated to do specific things at certain times. They don’t like trivial details and rules because those are not exciting. Enthusiasm is vital for ENFPs since it is their drive to function well. They can be highly passionate about things that they are excited about. Without it, they tend to become directionless and lacking in purpose.
    ENFPs are optimistic people. They radiate warm and fun energy wherever they step in. The positive aura that they give off is also very contagious. They have a distinct ability to spark light into their own lives, even during their darkest moments. With their youthful attitude at heart, ENFPs inspire and bring out the best and beauty in life.`},
    
    { type: 'ISTJ', description: 'Precision and Order Unlocked', details: `ISTJs are honest and responsible. People can count on their word, dependability, and long-term commitment, even during tough times. They will pay attention to and attend to your needs, bringing you the things that make you smile. You can count on them to do things the right way and cautiously, evaluating all facts and details. They may seem serious and wise on the surface, but deep down, they have a quirky and lovable sense of humor.
    These individuals are hard workers people can rely on to follow through on tasks. They see that everything is planned and fixed, from brainstorming to implementation. ISTJs enjoy authority over things because they are perfectionists and want everything to be up to a certain standard. Because of this, they may take for granted other people’s efforts and their own. They are not big fans of giving themselves credit because; they are merely doing their obligation. As people with a strong sense of duty and responsibility, ISTJs never second guess in taking complete accountability for their actions.
    ISTJs are a “slowly but surely” type of person. Typically, they work long hours and put a lot of effort into tasks given to them. They attend to every detail meticulously. ISTJs spend a lot of their time making sure that they deliver nothing but the best. They take pride in what they do. ISTJs have great focus, especially when it comes to doing essential tasks. Their unique capability is to ignore all the distractions that may come their way. They are hard workers and often expect everybody to do the same. They dislike inefficient people and those who leave out essential details when working.
    One of ISTJs' biggest desires is the recognition of society’s established norms and institutions. They will guard and protect traditions and culture from the past. ISTJs thrive in a life where there is order. Because of this belief, ISTJs are people who like planning and following certain routines, whether in their lives or their view of the world.
    You can trust an ISTJ to hold on to their promises. They are responsible and realistic at the same time. When ISTJs say something, they mean it and will work their best to achieve it. Although, sometimes, they may have difficulty passing on favors or be stubborn. This may lead to them being taken advantage of or hardwired to what they believe in. Often, ISTJs can’t accept when they are wrong.` },
    
    { type: 'ISFJ', description: 'Discover Nurturing Kindness', details: `ISFJs are supportive, reliable, and patient and are always available to help the people around them. A deep and unwavering devotion to protecting their loved ones is underneath their warm and selfless demeanor. They're humble and altruistic people who underplay their accomplishments and take their responsibilities seriously. They have many redeeming qualities that their many friends love.
    Warm and kind-hearted, ISFJs live with compassion, integrity, and practical kindness. They are good at keeping harmony. ISFJs are polite and generous individuals. For them, people should pay generosity with even more generosity. They are also conscious of others. They make sure that they feel seen, recognized, and appreciated.
    ISFJs are attached to familiarity. They find comfort in knowing that things have been done and tested in the past. Because of this, they are great bearers of traditions and rules. ISFJs believe that systems exist because they have a purpose. Often, it is hard for ISFJs to break out from a pattern or from what they've been used to. ISFJs would rather stick to familiarity than take risks. They are usually hesitant to change in the absence of concrete evidence.
    If there were people who would remember all the essential things, such as deadlines and special occasions, they would be the ISFJs. They are careful planners and observant of their surroundings. Their great memory and thoroughness aid in their dedication and thoughtfulness
    Naturally private and sensitive, ISFJs are likely to keep their feelings to themselves until they can't. ISFJs may struggle to separate their personal lives from their professional ones. They are good at sensing how other people feel, but when it comes to their own, that is not the case. ISFJs take everything emotionally. They may try to put on a brave face when with others, but deal with the hurt when back home.` },
    
    { type: 'ESTJ', description: 'Unyielding Pillars of Strength', details: `ESTJs are strong leaders who are dedicated, hard-working, honest, and reliable. Their no-nonsense, take-charge demeanor helps the people around them feel secure. You can count on them to be direct, whether telling the hard truth or not playing games when letting you know their interest. They value their friends and family and uphold the traditional values that keep family and society together.
    Systematic, organized, and straightforward, ESTJs place great importance on objectivity. They make sure to set their emotions aside when coming up with decisions. For them, emotions are not a priority. ESTJs see emotions as signs of weakness and a hindrance to achieving their goals. They typically deal with essential matters in an impersonal manner. ESTJs have a "cut to the chase" attitude since they are firm and direct. They dislike wasting time and are frank with their opinions and feedback. Because of their nature, they may come off as intimidating or harsh, but in reality, ESTJs mean well.
    ESTJs are moral and honest individuals. They despise cheating, laziness, and disobedience. They typically have strong principles that are hard to waver. ESTJs have a clear set of beliefs and a particular set of standards that they wish to be followed by everyone else.
    Uncertainties don't sit well with ESTJs. They thrive well when they know how everything works and when things are going according to how they are planned. ESTJs always want to be updated on what to expect. Making sure that everything is organized is something that ESTJs are obsessed with. When there is chaos, ESTJs usually tap on historical information. They check what methods or systems worked in the past and believe that they will work again in the present. ESTJs are comfortable with existing and established procedures.
    ESTJs are people who like taking charge. When ESTJs set a goal for themselves, they are unstoppable until that is achieved. They are willing to conquer the most challenging task to get what they want. They are efficient and capable of making complicated tasks easier. Putting plans into action and turning huge goals into simple steps is what ESTJs are great at. As goal-oriented people, ESTJs dislike when those around them fail to deliver. Frequently they may forget how other people may feel because they care about their demands more.` },
    
    { type: 'ESFJ', description: 'Connecting Caring Hearts!', details: `ESFJs are caring, loyal, and attentive to others’ needs, ensuring the people around them are taken care of. Often the social butterflies and center of a community, they empathize easily with others. People are drawn to their social grace, warmth, and no-nonsense practical nature. They do not shy away from commitments and responsibility and find possible solutions to help those struggling.
    As organizational enthusiasts, ESFJs like to plan everything, with whom the unknown does not sit well. ESFJs are not big fans of anything that is not solid and reliable, like abstracts, theories, concepts, and impersonal analysis. ESFJs crave a stable life, which is why they always see that everything is alright. ESFJs enjoy taking part in communities and organizations. Delivering more than what is expected from them is something people can always expect from ESFJs.
    Like how ESFJs value tradition, community, and morality. ESFJs frequently see no room for uncertainty. Everything is either black or white in their eyes. Their morality is mostly based on what society deems to be proper and wrong. They may be judgmental as a result, but only because of how they see the world and their desire to keep things in order.
    ESFJs often have high expectations of other people. They encourage them to pursue their full potential. Often, they refuse to see the bad in people – especially those close to them. They love helping and being selfless, but along with it, ESFJs wish to be seen and appreciated. When they are not noticed for what they do, ESFJs feel unmotivated or rejected. ESFJs are people pleasers and providers. They often have a strong desire to be in control and send as much help to others as possible. As someone obsessed with social status, ESFJs think about how others perceive them.` },
    
    { type: 'ISTP', description: `Practical Tinkerer's Secrets`, details:`ISTPs are cheerful, relaxed, and go with the flow personalities with great common sense and are skilled with their hands and tools. They are laid-back yet rebellious, intellectual, but chill. They are independent, self-sufficient, and far from clingy or desperate. Fluent in sarcasm, they kind of enjoy it when people can't tell if they're joking or actually serious.
    As rational and logical people, ISTPs aim to understand how things work. Typically, ISTPs are emotionally detached because they don't want their feelings to affect their decisions. They value results and actions over how other people would feel. They value logic and efficiency greatly and thus don't like talking much, especially about unimportant things. ISTPs are individuals with a great sense of practicality. They have a high focus and self-discipline regarding things they deem essential.
    ISTPs often have a unique ability in repairs and making things work again. They find happiness in tasks that require them to apply their logical skills and knowledge to analyze technicalities. ISTPs can see through every detail. They like taking things apart and checking if each part is working perfectly for the whole. The technical skills of ISTPs are unquestionable; they are great with tools and are exceptional at craftsmanship.
    Their various natural capabilities and skills in many different areas make ISTPs great at adapting to change. They often get bored with routines, and find planning and preparing for things before they happen highly stressful. They generally dislike being mandated and regulated. ISTPs thrive when they are allowed to work at their own pace. However, since they are adaptable individuals, ISTPs can adjust their mindset to fit into circumstances that need them. They can even compromise and collaborate with others when that is what the world demands from them.
    ISTPs are some of the most reliable when it comes to crises or emergencies. Their logical minds allow them to troubleshoot problems and tie loose ends faster than anyone else. ISTPs strive to come up with practical answers to the issues they encounter, interested in cause and effect relationships. Through that, they will be able to see where the problem came from, and they'll be able to solve it from there. This method will solve the current situation and prevent it from happening again.`  },
    
    { type: 'ISFP', description: 'Artful Souls Revealed', details: `ISFPs are creative, artistic, and spontaneous souls. They are fiercely individualistic and pride themselves on being outside the box and crushing labels and stereotypes. They are a mix of contradictions: empathetic yet mysterious, reserved but bold, and sensitive yet adventurous. They have a natural talent for aesthetics and know how to look good.
    As flexible and spontaneous individuals, ISFPs like to keep their options open. They ensure that they are leaving ample space for adventures and the unexpected. ISFPs see life as a sensation of possibilities, upsetting society’s expectations along the way. Because explorations and experiments are some of their greatest energizers, they tend to get involved in risky things.
    ISFPs are sensitive souls who are graceful, gentle, and typically soft-spoken. They are tolerant and accepting people who appreciate life as it is. Every encounter they've had holds a special place in their hearts. ISFPs always seem to consider compassion and consideration. Because of their ability to pick up even the unspoken, they know that they shouldn't judge other people. ISFPs decide based on their own subjective belief and believe in second chances.
    For ISFPs, actions are louder than words. They believe the best way to learn is to get their hands dirty with practical applications. Sitting in the corner and reading thick books with tons of abstract ideas and theories don't work for them. ISFPs are realistic dreamers who can balance creativity and logic. Because of their logical side, they can see patterns and look for opportunities for change.
    Creative and free-spirited, ISFPs are natural artists. They are attracted to beauty and typically have a strong appreciation for aesthetics. They have vivid imaginations, which they use to create different works of art. They dance to their own rhythm, doing the things they find beautiful.` },
    
    { type: 'ESTP', description: 'Excitement on the Edge!', details: `ESTPs are bold, direct, and entrepreneurial. They are the life of the party and live for adventure and a bit of danger. They are the quintessential bad boy or bad girl, charming with good humor and confidence. They are good at knowing how others are feeling and what they need. In crises where others panic, they face straight on.
    Often impatient with theories, ESTPs prefer practical facts rather than abstract ideas. For them, views only bear little importance to life. ESTPs often have problems in school because of this belief. Quick with decision-making, ESTPs solely base them on logical reasons and innovative solutions. 
    With their casual approach to life, ESTPs are often regarded as street-smart. ESTPs see that their options are always open; this may be one reason they like improvising more than planning. ESTPs are versatile individuals who are great at conquering problems that are on hand. They are great at grasping their environment, making them a few steps ahead of other people at most times. ESTPs welcome and embrace new challenges wherever they are.
    ESTPs are impulsive people. They often take risks even when it is not necessary. The "leap before you look" personality is prominent with ESTPs. There are situations where they may be overly caught up in the moment and insensitive. ESTPs tend to act or speak before thinking because of their impulsiveness.
    People can't expect ESTPs to slow down for them. They are fast-paced people; they like moving quickly and wish to skip life's serious and emotional parts. ESTPs are people of action who thrive in the physical environment. A lot of ESTPs are athletic and drawn to the physical lifestyle. They have kinesthetic intelligence and exceptional hand-eye coordination. They are some of the most coordinated people.` },
    
    { type: 'ESFP', description: 'When Life is a Party!', details:`ESFPs are the life of the party, and there's never a dull moment with them. They have great aesthetic tastes and people skills. People are drawn to them for their mix of charismatic social grace, enthusiastic warmth, and spontaneous adventure. They are masters of living in the moment, bringing joy and laughter to the people around them.
    "Go where the water takes you" is something that ESFPs live by. They are flexible, adaptable, resourceful, and outgoing. ESFPs believe they can handle things as they happen because they dislike preparing for what could be. ESFPs believe in growing as they go.
    ESFPs prefer following their own path and dislike people telling them which way they should go. As practical learners, ESFPs often have difficulty learning when trapped in a four-cornered room. For them, to learn is to experience.
    Warm, sympathetic, and fun-loving, it is a given that people love ESFPs, and they love them too. They have a keen sense of seeing people behind who they are trying to be, but rather who they are. ESFPs accept everyone, despite being aware of who they are inside. For them, to accept others is to allow them to enjoy themselves. They care about other people's feelings; thus, they are always ready to extend help.
    With their eye for beauty, ESFPs appreciate the finer things in life. They find happiness in having pretty things. ESFPs are known for being explorers of life's pleasures. Maybe that is why they always try and seek what it has to offer. ESFPs always follow the trends because of their strong sense of aesthetics. They are not just people and life-loving; they also adore material comforts.` },
];

export default function Perdata({ showSidebar }) {
    const [selectedPersonality, setSelectedPersonality] = useState(null);

    return (
        <div className="w-full h-screen flex flex-col items-center justify-start text-white border-black bg-[url('./assets/images/cartoon-bg.png')] bg-cover bg-fixed font-poppins">
            <Sidebar showSidebar={showSidebar} />
            {/* <h1 className="mt-[100px] ">16 Personalities</h1> */}
            <div className="flex flex-row gap-5 mt-[80px] ml-20">
                <div className="h-[320px] border-2 border-primary-pink rounded-[30px] bg-black bg-opacity-60 backdrop-blur-md p-6">
                    <h2 className='text-2xl mb-5'>personalities</h2>
                    <ul className='grid grid-cols-4 gap-4'>
                        {personalities.map((p) => (
                            <li className="flex justify-center items-center h-[20px] border-2 border-primary-pink rounded-[30px] text-white bg-black bg-opacity-60 backdrop-blur-md p-4" key={p.type}>
                                <button onClick={() => setSelectedPersonality(p)}>{p.type}</button>
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="flex h-auto w-[950px] border-2 border-primary-pink rounded-[30px] bg-black bg-opacity-60 backdrop-blur-md p-6">
                    {selectedPersonality ? (
                        <div className="personality-details">
                            <h2 className="flex justify-center text-2xl mb-5"> Who are {selectedPersonality.type} ? : {selectedPersonality.description}</h2>
                            <p>{selectedPersonality.details}</p>
                        </div>
                    ) : (
                        <p>Select a personality to see the details</p>
                    )}
                </div>
            </div>
        </div>
    );
}

// export default function Perdata({ showSidebar }){
//     return(
//         <div className="w-full h-screen flex flex-col items-center justify-center border-black bg-[url('./assets/images/cartoon-bg.png')] bg-cover bg-fixed font-poppins">
//             <Sidebar showSidebar={showSidebar}/>

//         </div>
//     )
// }